### ISSUE TITLE
Unable to make dashboards after using the group module

### ISSUE THREAD

**Issue by LexRillo** [emoncms/group#12]
I cannot create dashboards for a conflict between the Modules/graph/graph_model and Modules/graph/widget/graph_widget since the __construct method of Graph asks for mysqli and group and widget only uses mysqli. I have attached an image with the error print.
![errordashboard](https://user-images.githubusercontent.com/26965905/29667464-68af6096-88d4-11e7-8c03-332929bd1d3e.PNG)

**Comment by cagabi** [comment]
Hi Alejandro,

I am back now, catching up with things. I'll have a look into this soon.

  Carlos

**Comment by cagabi** [comment]
Hi, this is fixed now.
But I have just found a new bug #13, so you may want to wait to update the graph module until that gets fixed

**Comment by LexRillo** [comment]
The message has changed and the board is visible but now I get:
![groupmodule](https://user-images.githubusercontent.com/26965905/30032098-e95df40e-918b-11e7-905a-4c5f555a68e8.PNG)

**Comment by cagabi** [comment]
Hi, it looks like you haven't updated the graph module. Do it from the development branch: [graph module](https://github.com/carboncoop/graph/tree/develop)

**Comment by LexRillo** [comment]
Excelent. Now it works. I had updated group and dashboards. forgot about graphs
