### ISSUE TITLE
Impossible to click on groups or feeds to see graphs

### ISSUE THREAD

**Issue by LexRillo** [emoncms/group#14]
I updated all of the modules but I cannot expand the groups on the group page or expand the feeds on the graphs page. This means I cannot see the graphs for feeds or which feeds are on the group

**Comment by LexRillo** [comment]
OK. Now it works. I resintalled graphs and group modules again. I tried with the master branch of group and didnt work. I did it with the development one and it does. I should have done that test before but it didn't occur to me.

**Comment by cagabi** [comment]
No worries. Good it is working :)
