### ISSUE TITLE
Button to reset password + send login details to user

### ISSUE THREAD

**Issue by takkaria** [emoncms/group#48]
At the moment it is a manual process to send users their password if they are already created (e.g. using the script as has been used for Nobel Grid).  It would be good to be able to send passwords when editing a user, using some kind of editable template if possible.

**Comment by cagabi** [comment]
I am working on this now, so far the wildcards I have added are {{password}} and {{username}}.
Shall I add "Name" to the edit user modal and the {{name}} wildcard?

**Comment by cagabi** [comment]
I have done it:
 - Added 'Name' to the "Create user and add to group modal"
 - Added the send email feature to the edit user modal
 - Added inputs for email subject and body
 - Wildcards to use: {{name}}, {{username}}, {{password}}, {{role}}, {{appname}} (set in settings.php) and {{path}} (useful for making links. Hover the question marks on the modals for clarity

**Comment by cagabi** [comment]
Testing it in the server there seems to not be working

**Comment by cagabi** [comment]
Sorted

**Comment by takkaria** [comment]
Great, thanks!
