### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by reedy** [emoncms/group#57]
What's the license for this repo?

Is it AGPL-3.0-or-later as per https://github.com/emoncms/emoncms ?

**Comment by cagabi** [comment]
Not sure about the "later"
The only reference to licnse is what we added on the beginning of the files (like many other emonCMS files"

> All Emoncms code is released under the GNU Affero General Public License.

**Comment by reedy** [comment]
https://github.com/emoncms/emoncms/blob/master/COPYRIGHT.txt#L6-L9 says otherwise (at least for the main/central/whatever repo)

```
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or any later version.
```

**Comment by cagabi** [comment]
Do you think this module nee to have a similar copyright?

**Comment by reedy** [comment]
The module needs a copyright, yes. I'm not so bothered about what it is (IANAL), for ease, it's easier if it's the same as the parent project

I believe this counts as a derivative of https://github.com/emoncms/enomcms but don't quote me on that 

>We believe open source is a better way of doing things. Emoncms is available under the GPL Affero licence (AGPL).

So, as per https://help.github.com/en/articles/licensing-a-repository

>For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

:)

**Comment by cagabi** [comment]
I have added a copyright and copied the license. I think it should be now, have a look.
Thanks
